// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLnkEz4T2UijsswxW0LUFvo2qGV6I6mF4',
    appId: '1:310932018492:web:065a635e232a4e5059ba39',
    messagingSenderId: '310932018492',
    projectId: 'disasterbuddy-9f1ee',
    authDomain: 'disasterbuddy-9f1ee.firebaseapp.com',
    databaseURL: 'https://disasterbuddy-9f1ee-default-rtdb.firebaseio.com',
    storageBucket: 'disasterbuddy-9f1ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7kAOOy-IyFz8Pc_GJBE3OFomy7IZE_5E',
    appId: '1:310932018492:android:3d99a7908fdeffa159ba39',
    messagingSenderId: '310932018492',
    projectId: 'disasterbuddy-9f1ee',
    databaseURL: 'https://disasterbuddy-9f1ee-default-rtdb.firebaseio.com',
    storageBucket: 'disasterbuddy-9f1ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzVvbbXHwUwMvYH8CY7GERLuJXRdDnU0Y',
    appId: '1:310932018492:ios:f330a692c0751dba59ba39',
    messagingSenderId: '310932018492',
    projectId: 'disasterbuddy-9f1ee',
    databaseURL: 'https://disasterbuddy-9f1ee-default-rtdb.firebaseio.com',
    storageBucket: 'disasterbuddy-9f1ee.firebasestorage.app',
    iosBundleId: 'com.codeqo.disasteradvisor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzVvbbXHwUwMvYH8CY7GERLuJXRdDnU0Y',
    appId: '1:310932018492:ios:39af8598ba6a19cb59ba39',
    messagingSenderId: '310932018492',
    projectId: 'disasterbuddy-9f1ee',
    databaseURL: 'https://disasterbuddy-9f1ee-default-rtdb.firebaseio.com',
    storageBucket: 'disasterbuddy-9f1ee.firebasestorage.app',
    iosBundleId: 'com.example.disasterbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLnkEz4T2UijsswxW0LUFvo2qGV6I6mF4',
    appId: '1:310932018492:web:670190cb373dfc4259ba39',
    messagingSenderId: '310932018492',
    projectId: 'disasterbuddy-9f1ee',
    authDomain: 'disasterbuddy-9f1ee.firebaseapp.com',
    databaseURL: 'https://disasterbuddy-9f1ee-default-rtdb.firebaseio.com',
    storageBucket: 'disasterbuddy-9f1ee.firebasestorage.app',
  );
}
